#+OPTIONS: toc:nil
#+OPTIONS: num:nil

#+bibliography: /home/arcotpixel/research/bib/references.bib
#+CSL_STYLE: /home/arcotpixel/research/Zotero/styles/american-medical-association.csl

* Background:
Embryologically, the left brachiocephalic vein (LBV) originates as an anastamotic channel between the right and left /anterior/ cardinal veins [cite/Vancouver:@mozes_chapter_2007].
This positions the LBV between the manubrium sterni anteriorly and the aorta and innominate artery posteriorly [cite:@standring_grays_2015].
This pattern of adjacency of the aorta to the LBV is unique to mammals and results from a quirk of evolution [cite:@hirokawa_leftright_2009].
With age, the ascending aorta, unfolds, elongates and dilates [cite:@ohyama_imaging_2018].
Simultaneously, there is a change in the thoracic geometry that reduces the thoracic volume primarily from disc height loss and kyphosis [cite:@holcombe_age-related_2017].
These transitions progressively compress the LBV. Normally this compression is circumvented via collateral pathways and "Blood finds a way" [cite:@marini_blood_2019].
However "What if these collaterals are insuffcicient?" is a question that has not been answered. It is possible that there is no clinical detriment and this is just an innocuous finding.
On the contrary, it may signal a whole class of neurological disorders and explain the pathophysiology of hitherto unexplained neurological and neurodegenrative conditions.

* Embryology, Anatomy and Radiology:
The anterior cardinal veins drain the cephalic portion of the embryo.
During week eight of development the thyroid and thymic veins join to form a large transverse anastamosis superior to the common cardinal veins.
This anastamosis allows blood from the cephalic portion of left anterior cardinal vein (future left internal jugular vein) to reach the junction of the right anterior cardinal vein (future right internal jugular vein) and right common cardinal vein (future superior venacava (SVC)).
Various developmental venous malformations (left sided SVC, double SVC) may occur if the above does not proceed according to plan [cite:@white_anatomy_2022].
Normally however, one ends up with an efficent LBV that transports blood from the left internal jugular vein to the SVC. Until, of course, it is smothered by its more sturdy anatomical neighbours.

Symmetry breakdown in the embryo reults in a left-right patterning of organs [cite:@hirokawa_leftright_2009].
This process is consistent and normally results in a left sided aorta in mammals.
As the aorta loops to the left it gives rise to the innominate artery which courses back across the midline.
This midline in the superior mediastinum is crowded and contains the thymus, left brachiocephalic vein, aortic arch, innominate artery, trachea and the esophagus bounded by the sternum anteriorly and the thoracic vertebrae posteriorly [cite:@stoddard_anatomy_2022].
With aging, the aorta and innominate artery elongate, stiffen and dilate [cite:@ohyama_imaging_2018].
The trachea and esophagus also simultaneously stiffen [cite:@gregersen_deterioration_2008; @safshekan_mechanical_2016].
The thymus involutes and is replaced by fatty tissue [cite:@rezzani_thymus_2014].
This leaves a hapless left brachiocephalic vein with no prospects and a gradual extrinsic compresssion ensues.
Collateral flow begins to increase via multiple possible pathways [cite:@meier_venous_2019] and for a while there is no discernible effect.
Eventually, in some individuals the venous collaterals will not suffice and symptoms will ensue.

This entity is notoriously hard to diagnose via convesntional non invasive techniques.
It is nearly impossible to pick it up on CT angiograms that are obtained with right arm injections.



* Discussion:


#+BIBLIOGRAPHY: here
