#+OPTIONS: toc:nil
#+OPTIONS: num:nil

#+bibliography: /home/arcotpixel/research/bib/references.bib
#+CSL_STYLE: /home/arcotpixel/research/Zotero/styles/american-medical-association.csl
* Syndrome Sinistre: Left Brachiocephalic Vein Compression as an insidious cause of Neurological Disorders
* Background:
Embryologically, the left brachiocephalic vein (LBV) originates as an anastamotic channel between the right and left /anterior/ cardinal veins [cite/Vancouver:@mozes_chapter_2007].
This positions the LBV between the manubrium sterni anteriorly and the aorta and innominate artery posteriorly [cite:@standring_grays_2015].
This pattern of adjacency of the aorta to the LBV is unique to mammals and results from a quirk of evolution [cite:@hirokawa_leftright_2009].
With age, the ascending aorta, unfolds, elongates and dilates [cite:@ohyama_imaging_2018].
Simultaneously, there is a change in the thoracic geometry that reduces the thoracic volume primarily from disc height loss and kyphosis [cite:@holcombe_age-related_2017].
These transitions progressively compress the LBV. Normally this compression is circumvented via collateral pathways and "Blood finds a way" [cite:@marini_blood_2019].
However "What if these collaterals are insuffcicient?" is a question that has not been answered. It is possible that there is no clinical detriment and this is just an innocuous finding.
On the contrary, it may signal a whole class of neurological disorders and explain the pathophysiology of hitherto unexplained neurological and neurodegenrative conditions.

* Embryology, Anatomy and Radiology:
The anterior cardinal veins drain the cephalic portion of the embryo.
During week eight of development the thyroid and thymic veins join to form a large transverse anastamosis superior to the common cardinal veins.
This anastamosis allows blood from the cephalic portion of left anterior cardinal vein (future left internal jugular vein) to reach the junction of the right anterior cardinal vein (future right internal jugular vein) and right common cardinal vein (future superior venacava (SVC)).
Various developmental venous malformations (left sided SVC, double SVC) may occur if the above does not proceed according to plan [cite:@white_anatomy_2022].
Normally however, one ends up with an efficent LBV that transports blood from the left internal jugular vein to the SVC. Until, of course, it is smothered by its more sturdy neighbours.

The LBV vein is approximately 6 cm to 7 cm long. It is formed by the confluence of the left internal jugular vein and the left subclavian vein behind the left sternoclavicular joint.
It then runs and obliuqe and downward course to the right to join the right brachiocephalic vein and form the superior vena cava behind the sternum and the first intercostal space.
In its course, it receives the the following veins: left  vertebral, left inferior thyroid, left internal thoracic, left superior intercostal, left supreme intercostal, thymic and pericardiacophrenic veins.
Its relations with its less compliant neighbours forms the crux of this syndrome.
It initially runs anterior to the parietal pleura of the lung and then enters a valley between the bony manubrium anteriorly and an unyielding innominate artery posteriorly [cite:@standring_grays_2015].
It is in this valley that the LBV gets trapped usually for a few millimeters congruent with the portion in contact with the innominate artery.

The radiological findings are often obvious but the apparent lack of clinical relevance lends to under reporting.
As an example, osteporotic vertebral fractures suffer a similar fate [cite:@williams_under-reporting_2009].
There are excellent examples of LBV compression with resultant venous reflux on CT angiography [cite:@seth_intracranial_2022; @tseng_venous_2007].
Similar findings are noted on MR Venography [cite:@han_obstruction_2015].
Intravascular ultrasound however appears to be the the new "gold standard" especially if right sided injections are performed for CT angiography and MR venography of the neck does not extend down to the level of the LBV.


* Discussion:
LBV compression should be expected to occur and progress with aging due to the anatomical factors described above.
It should generally be asymptomatic given the remarkable redundancy of the venous system and its collaterals.
Symptoms should and do ensue when the venous collaterals are either insufficient or overwhelmed.
This can be compounded by venous obstruction on the contralteral side, which is not uncommon.
For example, trapping of the right internal jugular vein at the level of the C1 transverse process.
In fact it might be necesary for bilateral outflow obstruction given the nature of the connections between the dural sinuses.
This results in the emergence of two pathophysiological states.
One governed by a build up of pressure due to venous hypertension and the other governed by stagnation / venous congestion.
The venous hypertensive state could potentially explain the mechanical effects such as headache and disorders that arise from obstruction of csf.
Accumulation of toxic waste metabolites [cite:@cheng_how_2019] due to poor venous outflow could potentially explain the chemical effects that lead to neurodegenration.
Clinically, in my experience, there appears to be a predeliction for headaches, vertigo, tinnitus, deafness and imbalance.
Ageing is a risk factor for neurodegenerative disease [cite:@hou_ageing_2019] and ageing is a risk factor for LBV compression.
Is it possible that the LBV compression is an important precursor to neurodegenrative diseases?

* Conclusion:
There have been multiple attempts to link singular neurological disorders to venous outflow obstruction.
The prime example was chronic cerebro spinal venous insufficiency which tied itself to multiple sclerosis [cite:@zamboni_chronic_2009].
It was heralded by a flurry of research which simply imploded when the initial results were not widely repoducible [cite:@baracchini_ccsvi_2012].
This may have been responsible for the general perecption of dubiousness and outright opposition to venous procedures for neurological disorders.
As another example, transverse sinus stenosis as a cause of intracranial hypertension, is a more recent association that appears in need of definitive evidence to become widely accepted [cite:@gurney_pexploring_2020].
The list continues on with conditions such as transient global amnesia [cite:@han_obstruction_2015], deafness [cite:@griffith_venous_1961], Normal Pressure Hydeocephalus [cite:@satow_alteration_2017] and so on.

One could argue that a more holistic approach is in order.
If such an approach was applied, the entire class of disorders, neurological or otherwise would come under an umbrella term such as Venous Outflow Obstruction Disorders (Voodoo).
The venous hierarchy (for the superior vena caval system) would be along anatomical lines beginning with the cortical veins, coursing through the superior sagittal, inferior sagittal and straight sinuses, moving on to the transverse and signoid sinuses, followed by the paired jugular and brachiocephalic veins with the superior venacava and the right heart, pulmonary arteries and left heart forming the inferior portions.
Theoretically, any dowstream segment in the hierarchy should be able to affect any upstream segment and produce its congruent disorder.
For example, one should not be surprised when superior vena caval stenosis produces papilledema in a patient and similarly not be surprised if transverse sinus stenting does not relieve the papilledema in said patient.
Thus it would be important to evaluate the entire pathway and treat tandem lesions, in some cases bilaterally in order to provide good venous outflow from both the superficial and deep pathways.

LBV compression would fall into this class of disorders. The neurological symptoms would depend on the drainage pathway that was affected.
On the surface, this condition  appears to associated with seemingly innocuous complaints such as headache and vertigo.
At a deeper level it may be a precursor to more sinister neurodegenrative disorders.
Given the technical ease of its treatment with stenting, it represents a serious target for further research.



#+BIBLIOGRAPHY: here
